#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Creston Bunch"
email = "git@bunch.im"

[ui]
diff-editor = "diffview"
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[merge-tools.diffview]
# https://github.com/jj-vcs/jj/wiki/Vim,-Neovim
program = "sh"
edit-args = ["-c", '''
  set -eu
  rm -f "$right/JJ-INSTRUCTIONS"
  git -C "$left" init -q
  git -C "$left" add -A
  git -C "$left" commit -q -m baseline --allow-empty
  mv "$left/.git" "$right"
  (cd "$right"; nvim -c DiffviewOpen)
  # git -C "$right" add -p
  git -C "$right" diff-index --quiet --cached HEAD && { echo "No changes done, aborting split."; exit 1; }
  git -C "$right" commit -q -m split
  git -C "$right" restore . # undo changes in modified files
  git -C "$right" reset .   # undo --intent-to-add
  git -C "$right" clean -q -df # remove untracked files
''',
]
